/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TesisRouteImport } from './routes/tesis'
import { Route as ProduccionRouteImport } from './routes/produccion'
import { Route as MateriasRouteImport } from './routes/materias'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const TesisRoute = TesisRouteImport.update({
  id: '/tesis',
  path: '/tesis',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduccionRoute = ProduccionRouteImport.update({
  id: '/produccion',
  path: '/produccion',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriasRoute = MateriasRouteImport.update({
  id: '/materias',
  path: '/materias',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/materias': typeof MateriasRoute
  '/produccion': typeof ProduccionRoute
  '/tesis': typeof TesisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/materias': typeof MateriasRoute
  '/produccion': typeof ProduccionRoute
  '/tesis': typeof TesisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/materias': typeof MateriasRoute
  '/produccion': typeof ProduccionRoute
  '/tesis': typeof TesisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/materias'
    | '/produccion'
    | '/tesis'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/dashboard' | '/materias' | '/produccion' | '/tesis'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/materias'
    | '/produccion'
    | '/tesis'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  MateriasRoute: typeof MateriasRoute
  ProduccionRoute: typeof ProduccionRoute
  TesisRoute: typeof TesisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tesis': {
      id: '/tesis'
      path: '/tesis'
      fullPath: '/tesis'
      preLoaderRoute: typeof TesisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produccion': {
      id: '/produccion'
      path: '/produccion'
      fullPath: '/produccion'
      preLoaderRoute: typeof ProduccionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materias': {
      id: '/materias'
      path: '/materias'
      fullPath: '/materias'
      preLoaderRoute: typeof MateriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  MateriasRoute: MateriasRoute,
  ProduccionRoute: ProduccionRoute,
  TesisRoute: TesisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
