// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseClient() {
  // Client: Vite inlines VITE_* at build time. SSR on Vercel: read process.env at
  // runtime (dashboard vars) so missing build-time VITE_ does not break the server.
  const isSsr = import.meta.env.SSR;
  const SUPABASE_URL = isSsr
    ? process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL
    : (import.meta.env.VITE_SUPABASE_URL as string | undefined);
  const SUPABASE_PUBLISHABLE_KEY = isSsr
    ? process.env.SUPABASE_PUBLISHABLE_KEY || process.env.VITE_SUPABASE_PUBLISHABLE_KEY
    : (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined);

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    throw new Error(
      isSsr
        ? "Supabase: define SUPABASE_URL y SUPABASE_PUBLISHABLE_KEY en el proyecto (Vercel → Settings → Environment Variables) para el runtime del servidor."
        : "Supabase: define VITE_SUPABASE_URL y VITE_SUPABASE_PUBLISHABLE_KEY (variables de build para el cliente).",
    );
  }

  // En Node/SSR (p. ej. Vercel), persistSession + storage undefined puede romper el SDK; en el navegador va con localStorage.
  if (isSsr) {
    return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        persistSession: false,
        autoRefreshToken: false,
        storage: undefined,
      },
    });
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

